# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/refs/tags/v0.55.1/schema/config.json
git:
  pagers:
    - pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  spinner:
    frames:
      - "\U0001F311" # new moon
      - "\U0001F312" # waxing crescent
      - "\U0001F313" # first quarter
      - "\U0001F314" # waxing gibbous
      - "\U0001F315" # full moon
      - "\U0001F316" # waning gibbous
      - "\U0001F317" # last quarter
      - "\U0001F318" # waning crescent
    # The "speed" of the spinner in milliseconds.
    rate: 40
  theme:
    inactiveBorderColor:
      - "#e6edf3"
    defaultFgColor:
      - "#e6edf3"
    cherryPickedCommitFgColor:
      - "#d2a8ff"
    cherryPickedCommitBgColor:
      - "#e6edf3"
    activeBorderColor:
      - "#AB8DFF"
      - "bold"
    unstagedChangesColor:
      - "#f85149"
    selectedLineBgColor:
      - "#304d75"
    searchingActiveBorderColor:
      - "#e6edf3"
      - "bold"
    optionsTextColor:
      - "#d2a8ff"
os:
  editPreset: "nvim-remote"
